spring:
  application:
    name: payment_service
  flyway:
    enabled: true
    schemas: ateupeonding_payment_flyway
    user: postgres
    password: postgres
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/ateupeonding
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/ateupeonding
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:localhost}:5432/ateupeonding
    username: postgres
    password: postgres
    properties:
      schema: ateupeonding_payment
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    password: password
    username: rabbitmq

server:
  port: 8082
